### ISSUE TITLE
TypeError: super() argument 1 must be type, not None while install Sphnixcontrib-fulltoc

### ISSUE THREAD

**Issue by Ashroyal** [hasura/docs#148]
While install requirements its giving me a error 

Collecting sphinxcontrib-fulltoc
  Using cached sphinxcontrib-fulltoc-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /private/var/folders/93/_381xrh12xb7xyxrxb0_hb6c0000gn/T/pip-build-wFM47z/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/private/var/folders/93/_381xrh12xb7xyxrxb0_hb6c0000gn/T/pip-build-wFM47z/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/private/var/folders/93/_381xrh12xb7xyxrxb0_hb6c0000gn/T/pip-build-wFM47z/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/private/var/folders/93/_381xrh12xb7xyxrxb0_hb6c0000gn/T/pip-build-wFM47z/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2347, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 43, in <module>
        from sphinx.util.tags import Tags
      File "/usr/local/lib/python2.7/site-packages/sphinx/util/tags.py", line 11, in <module>
        from jinja2 import nodes
      File "/usr/local/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/usr/local/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/usr/local/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/local/lib/python2.7/site-packages/typing.py", line 1265, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    error in setup command: Error parsing /private/var/folders/93/_381xrh12xb7xyxrxb0_hb6c0000gn/T/pip-build-wFM47z/sphinxcontrib-fulltoc/setup.cfg: TypeError: super() argument 1 must be type, not None

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/93/_381xrh12xb7xyxrxb0_hb6c0000gn/T/pip-build-wFM47z/sphinxcontrib-fulltoc/

**Comment by paranoidsp** [comment]
This is on a mac right?  
Is this trying to install sphinx version 1.6.3?
Can you also give us the pip version and your macOS version?

**Comment by ecthiender** [comment]
I think its a Python version problem. Looks like you are using Python 2.7.
This docs works only on Python 3.

**Comment by ecthiender** [comment]
Apologies. Just tested, it seems to work fine on Arch Linux with Python2.7. The installed Sphinx version is 1.6.3.

Can you report the versions of different things you are using?
- OS
- Python version
- pip version
- Sphinx version (that might have got installed)
- And are you running inside a virtualenv?

**Comment by Ashroyal** [comment]
Hi ecthiender

- Mac OS x Sierra 
- pip version 9.0.1
- Python version 2.7
- Sphinx-1.6.3

**Comment by ecthiender** [comment]
It looks like it is a Sphinx error:

https://encrypted.google.com/search?hl=en&q=sphinx+TypeError%3A+super%28%29+argument+1+must+be+type%2C+not+None

With versions 1.6.x. We will try to downgrade Sphinx and try and get back
to you.

**Comment by Ashroyal** [comment]
Working fine when i downgraded sphinx to 1.5.6

**Comment by dsandip** [comment]
@ecthiender @vksci123 : Can we specify the Sphinx version in the requirements.txt file?

**Comment by dsandip** [comment]
@ecthiender @karthikvt26 : can you respond to my previous comment and close this please?

**Comment by karthikvt26** [comment]
Hi Sandip, I will add it and update.

**Comment by rikinsk** [comment]
Closing this.
